### ISSUE TITLE
'Transaction' object has no attribute 'write_testcase'

### ISSUE THREAD

**Issue by ignatenkobrain** [openSUSE/libsolv#202]
```python
[brain@ignatenko-w541 tmp]$ python3 -c "import solv; solv.Pool().Solver().transaction().write_testcase()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python3.6/site-packages/solv.py", line 1843, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, Transaction, name)
  File "/usr/lib64/python3.6/site-packages/solv.py", line 80, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'Transaction' object has no attribute 'write_testcase'
```

I see it in `solv.i`, but somehow it doesn't end up in target bindings....

**Comment by ignatenkobrain** [comment]
I'm blind, it is on solver, not on transaction =(
