### ISSUE TITLE
libsolv fails with Python 3.10: _solv.so: undefined symbol: PyObject_AsReadBuffer

### ISSUE THREAD

**Issue by hroncok** [openSUSE/libsolv#410]
Hello. In Fedora, we mass rebuild our packages with early versions of Python 3.10 to make sure everything will work flawlessly.

Unfortunately, packages using libsolv fail to build with errors like:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/builddir/build/BUILD/fedmod-0.6.3/_fedmod/cli.py", line 8, in <module>
    from . import _fetchrepodata, _repodata
  File "/builddir/build/BUILD/fedmod-0.6.3/_fedmod/_repodata.py", line 7, in <module>
    import solv
  File "/usr/lib64/python3.10/site-packages/solv.py", line 15, in <module>
    import _solv
ImportError: /usr/lib64/python3.10/site-packages/_solv.so: undefined symbol: PyObject_AsReadBuffer
```

From https://docs.python.org/3.10/whatsnew/3.10.html#id4

> PyObject_AsCharBuffer(), PyObject_AsReadBuffer(), PyObject_CheckReadBuffer(), and PyObject_AsWriteBuffer() are removed. Please migrate to new buffer protocol; PyObject_GetBuffer() and PyBuffer_Release().

https://bugs.python.org/issue41103

Disclaimer: I don't know anything about libsolv, but if you need help with migrating to new buffer protocol, please let me know.

**Comment by mlschroe** [comment]
I'll switch over to `PyBytes_AsStringAndSize()` for python3

**Comment by mlschroe** [comment]
Fixed, thanks for the report!

**Comment by hroncok** [comment]
Thank you very much for the super fast response Michael, I'm trying to test this but I was not successful so far.

**Comment by hroncok** [comment]
Seems like the generated file x86_64-redhat-linux-gnu/bindings/python/solv_python.c has:

```c
SWIGINTERN PyObject *_wrap_Chksum_from_bin(PyObject *SWIGUNUSEDPARM(self), PyObject *args) {
  PyObject *resultobj = 0;
  Id arg1 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  size_t arg3 ;
  int val1 ;
  int ecode1 = 0 ;
  int res2 ;
  char *buf2 = 0 ;
  size_t size2 = 0 ;
  int alloc2 = 0 ;
  PyObject *swig_obj[2] ;
  Chksum *result = 0 ;
  
  if (!SWIG_Python_UnpackTuple(args, "Chksum_from_bin", 2, 2, swig_obj)) SWIG_fail;
  ecode1 = SWIG_AsVal_int(swig_obj[0], &val1);
  if (!SWIG_IsOK(ecode1)) {
    SWIG_exception_fail(SWIG_ArgError(ecode1), "in method '" "Chksum_from_bin" "', argument " "1"" of type '" "Id""'");
  } 
  arg1 = (Id)(val1);
  res2 = SWIG_AsCharPtrAndSize(swig_obj[1], &buf2, &size2, &alloc2);
  if (buf2 && size2)
  size2--;
  
  if (!SWIG_IsOK(res2)) {
    const void *pybuf = 0;
    Py_ssize_t pysize = 0;
    
    
    
    res2 = PyObject_AsReadBuffer(swig_obj[1], &pybuf, &pysize);
    
    if (res2 < 0) {
      SWIG_exception_fail(SWIG_ArgError(res2), "in method '" "Chksum_from_bin" "', argument " "2"" of type '" "BinaryBlob""'");
    } else {
      buf2 = (void *)pybuf;
      size2 = pysize;
    }
    
    
    
  }
  arg2 = (unsigned char *)buf2;
  arg3 = size2;
  result = (Chksum *)Chksum_from_bin(arg1,(unsigned char const *)arg2,arg3);
  resultobj = SWIG_NewPointerObj(SWIG_as_voidptr(result), SWIGTYPE_p_Chksum, SWIG_POINTER_OWN |  0 );
  return resultobj;
fail:
  return NULL;
}
```

**Comment by hroncok** [comment]
If I remove the `PY_VERSION_HEX >= 0x03000000` conditional and end up with:

```diff
-    res = PyObject_AsReadBuffer($input, &pybuf, &pysize);
+    res = PyBytes_AsStringAndSize($input, &pybuf, &pysize);
```

It works.

**Comment by mlschroe** [comment]
Bah. I need to escape the preprocessor directives  so that they don't get removed by swig. Now done in commit e258226c2430db4f37a34c71e72b2d909fa407fe

**Comment by hroncok** [comment]
Thanks, that fixes it.
